// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuhsmGSja2nC5qj-lbOsAJ0BZpetYOvIU',
    appId: '1:124224713822:web:e8fc543830206d4411b0cf',
    messagingSenderId: '124224713822',
    projectId: 'aura3-74015',
    authDomain: 'aura3-74015.firebaseapp.com',
    storageBucket: 'aura3-74015.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-0h0XeA2RnQbKH1L6PXu-byDynq_cafo',
    appId: '1:124224713822:android:c7e69df0f16e3cc311b0cf',
    messagingSenderId: '124224713822',
    projectId: 'aura3-74015',
    storageBucket: 'aura3-74015.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe6r1JF1TFe_NgXeT7rKWvk7Ee_m5qim4',
    appId: '1:124224713822:ios:2ef8c78d5631360011b0cf',
    messagingSenderId: '124224713822',
    projectId: 'aura3-74015',
    storageBucket: 'aura3-74015.firebasestorage.app',
    iosBundleId: 'com.example.aura3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe6r1JF1TFe_NgXeT7rKWvk7Ee_m5qim4',
    appId: '1:124224713822:ios:2ef8c78d5631360011b0cf',
    messagingSenderId: '124224713822',
    projectId: 'aura3-74015',
    storageBucket: 'aura3-74015.firebasestorage.app',
    iosBundleId: 'com.example.aura3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuhsmGSja2nC5qj-lbOsAJ0BZpetYOvIU',
    appId: '1:124224713822:web:64bbd0e36b5393e711b0cf',
    messagingSenderId: '124224713822',
    projectId: 'aura3-74015',
    authDomain: 'aura3-74015.firebaseapp.com',
    storageBucket: 'aura3-74015.firebasestorage.app',
  );
}
